export class Usuario {
  constructor(
    public readonly id: bigint,
    public readonly publicId: string,
    public rolId: bigint,
    public nombres: string,
    public apellidos: string,
    public email: string,
    public telefono: string | null,
    public passwordHash: string,
    public codigoReferido: string | null,
    public activo: boolean,
    public ultimoAccesoEn: Date | null,
    public readonly creadoEn: Date,
    public readonly actualizadoEn: Date,
  ) {}

  static crear(
    rolId: bigint,
    nombres: string,
    apellidos: string,
    email: string,
    passwordHash: string,
    telefono?: string,
    codigoReferido?: string,
  ): Usuario {
    return new Usuario(
      0n, // Temporal ID before DB persistence
      '', // UUID will be generated by Postgres
      rolId,
      nombres,
      apellidos,
      email,
      telefono || null,
      passwordHash,
      codigoReferido || null,
      true,
      null,
      new Date(),
      new Date(),
    );
  }

  desactivar(): void {
    this.activo = false;
  }

  activar(): void {
    this.activo = true;
  }

  cambiarRol(nuevoRolId: bigint): void {
    this.rolId = nuevoRolId;
  }

  cambiarPassword(nuevoHash: string): void {
    this.passwordHash = nuevoHash;
  }

  actualizarPerfil(nombres: string, apellidos: string, telefono: string | null): void {
    this.nombres = nombres;
    this.apellidos = apellidos;
    this.telefono = telefono;
  }

  registrarAcceso(): void {
    this.ultimoAccesoEn = new Date();
  }
}
